export const theme = {
  colors: {
    background: '#F8FAFC',
    card: '#FFFFFF',
    primary: '#0F172A',
    primaryDark: '#1E293B',
    accent: '#3B82F6',
    success: '#10B981',
    warning: '#F59E0B',
    danger: '#DC2626',
    error: '#DC2626',
    info: '#3B82F6',
    text: '#0F172A',
    textMuted: '#64748B',
    border: '#E2E8F0',
    white: '#FFFFFF',
    softBlue: '#EFF6FF',
    softRed: '#FEF2F2',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 24,
    xl: 32,
    xxl: 48,
  },
  radius: {
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
    full: 9999,
  },
  typography: {
    h1: 32,
    h2: 24,
    h3: 20,
    body: 16,
    caption: 12,
  },
  shadows: {
    sm: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
      elevation: 2,
    },
    md: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 4,
    },
    lg: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 8,
    },
  },
} as const;
